fluentd:
  # path of logfiles, default /var/log/containers/*.log
  path: /var/log/containers/*.log
  # paths of logfiles to exclude. object type is array as per fluentd specification:
  # https://docs.fluentd.org/input/tail#exclude_path
  exclude_path:
    - /var/log/containers/*.log
  #  - /var/log/containers/tiller*.log
  #  - /var/log/containers/*_kube-system_*.log (to exclude `kube-system` namespace)

splunk:
  hec:
    host: 51.250.7.127
    indexName: test-osquery
    insecureSSL: true

logs:
  # we want to read logs for `kube-apiserver` from a log file other then from the container logs
  kube-apiserver:
    from:
      file:
        path: /var/log/kube-apiserver.log
  # read log files other then the default ones
  my-log-file:
    from:
      file:
        path: /var/log/osquery/*.log
    #timestampExtraction:
     # regexp: (?<time>\d{4}-\d{2}-\d{2}T\d{2}\d{2}\d{2}Z)
      #format: "%Y-%m-%dT%H:%M:%SZ"
    #multiline:
     # firstline: \d{4}-\d{2}-\d{2}
    sourcetype: "combined_access"
  # only multiline
  my-multiline-file:
    from:
      file:
        path: /var/log/my-multiline.log
   # multiline:
      #firstline: \d{4}-\d{2}-\d{2}
    sourcetype: "some:sourcetype"
  # no multiline
  my-json-file:
    from:
      file:
        path: /var/log/web-access.json
    timestampExtraction:
      regexp: (?<time>\d{4}-\d{2}-\d{2}T\d{2}\d{2}\d{2}Z)
      format: "%Y-%m-%dT%H:%M:%SZ"
    sourcetype: "_json"
  # no timestampExtraction
  my-data-file:
    from:
      file:
        path: /var/log/my-data.csv
    sourcetype: "csv"